version: '3.9'

services:
  web:
    build: ./backend
    command: ["/app/entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres:15
    restart: always
    environment:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: