# Generated by Django 5.2.1 on 2025-05-29 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_hash', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('subject', models.CharField(max_length=255)),
                ('company_ids', models.TextField()),
                ('contact_ids', models.TextField(blank=True, null=True)),
                ('candidature_ids', models.TextField(blank=True, null=True)),
                ('relance_ids', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
