# Generated by Django 5.2.1 on 2025-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appel',
            name='candidature',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='relance',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='user',
        ),
        migrations.AddField(
            model_name='appel',
            name='candidature_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='entreprise_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='relance_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
