# Generated by Django 5.2.1 on 2025-06-03 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0004_remove_appel_date_time_appel_contact_id_appel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
