# Generated by Django 5.2.1 on 2025-06-03 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0003_remove_appel_candidature_remove_appel_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appel',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appel',
            name='contact_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 3, 21, 4, 59, 477407, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='duree_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appel',
            name='candidature_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appel',
            name='entreprise_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
