# Generated by Django 5.2.1 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_delete_candidaturecontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='platform',
            new_name='plateform',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='candidature_id',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='candidature_status',
            field=models.CharField(choices=[('WAITING', 'En attente'), ('TO_BE_FOLLOWED', 'À relancer'), ('INTERVIEW_PENDING', 'Entretien à venir'), ('REJECTED_WITHOUT_INTERVIEW', 'Refus sans entretien'), ('REJECTED_AFTER_INTERVIEW', 'Refus après entretien')], max_length=100),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='candidature_type',
            field=models.CharField(choices=[('SPONTANEOUS', 'Spontanée'), ('OFFER', 'Offre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
