# Generated by Django 5.2.1 on 2025-06-03 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0003_rename_platform_candidature_plateform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='plateform',
            new_name='plateforme',
        ),
    ]
