# Generated by Django 5.2.1 on 2025-05-29 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_hash', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('candidature_id', models.UUIDField()),
                ('entreprise_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('candidature_date', models.DateTimeField()),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('candidature_type', models.CharField(max_length=255)),
                ('candidature_status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidatureContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidature_id', models.UUIDField()),
                ('contact_id', models.UUIDField()),
            ],
            options={
                'unique_together': {('candidature_id', 'contact_id')},
            },
        ),
    ]
