# Generated by Django 5.2.1 on 2025-06-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='appel_ids',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='candidature_ids',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='company_ids',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='entretien_ids',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='relance_ids',
        ),
    ]
