# Generated by Django 5.2.1 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_appel_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entreprise_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sync_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['entreprise_id'], name='contacts_co_entrepr_250211_idx'),
        ),
    ]
