# Generated by Django 5.2.1 on 2025-05-29 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_hash', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_interview_notes', models.TextField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('post_interview_notes', models.TextField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('tests_needed', models.BooleanField(default=False)),
                ('tests_deadline', models.DateTimeField(blank=True, null=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatures.candidature')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
