# Generated by Django 5.2.1 on 2025-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='candidature',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='company',
        ),
        migrations.AddField(
            model_name='entretien',
            name='candidature_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='entreprise_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
