# Generated by Django 5.2.1 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entretiens', '0002_remove_entretien_candidature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='candidature_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='entreprise_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
