# Generated by Django 5.2.1 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
